---
- name: "Postinstall with Ansible and Git"
  hosts: localhost
  connection: local
  
  pre_tasks:
    - include: "{{dist}}/tasks/repos.yml"
        
  tasks:
    - include: "{{dist}}/tasks/packages.yml"
    - include: "{{dist}}/tasks/docker.yml"
    - include: "{{dist}}/tasks/virtualcam.yml"
    - include: "{{dist}}/tasks/confs.yml"

  post_tasks:
    - name: Cleanup
      apt:
        autoremove: yes
        purge: yes

