---
- name: "Postinstall with Ansible and Git"
  hosts: localhost
  # strategy: mitogen_linear
  connection: local
  roles:
    - "{{ flavor }}"
################################# DEBUG #################################
- hosts: localhost
  connection: local
  tasks:
    - name: OS and Kernel info
      debug:
        msg: "{{ msg.split('\n') }}"
      vars:
        msg: |
          Distribution: {{ ansible_distribution }}
          Release: {{ ansible_distribution_release }}
          Distribution Version: {{ ansible_distribution_version }}
          Distribution Major Version: {{ ansible_distribution_major_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
        
          
    # - name: Display all variables/facts known for a host
    #   debug:
    #     var: hostvars[inventory_hostname]
    #   tags: debug_info
#########################################################################
