---
- name: "Postinstall with Ansible and Git"
  hosts: localhost
  strategy: mitogen_linear
  connection: local
  
  pre_tasks:
    - include: "{{dist}}/tasks/repos.yml"
    - name: Update cache
      apt:
        update_cache: yes
        
  tasks:
    - include: "{{dist}}/tasks/packages.yml"
    - include: "{{dist}}/tasks/docker.yml"
    - include: "{{dist}}/tasks/virtualcam.yml"
  
  post_tasks:
    - include: "{{dist}}/tasks/confs.yml"
    - name: Cleanup
      apt:
        autoremove: yes
        purge: yes

