#########################################################################################
- name: CONFS ROOT
  lineinfile:
    path: "{{item.path}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  loop:
    - { path: '/etc/default/tor', regexp: 'RUN_DAEMON="yes"', line: 'RUN_DAEMON="no"' }
#########################################################################################
- name: CONFS {{current_user}}
  shell: "{{item}}"
  become: true
  become_user: "{{current_user}}"
  loop:
    # VSCODE
    - code --install-extension alexkrechik.cucumberautocomplete
    - code --install-extension vscoss.vscode-ansible
    - code --install-extension ms-azuretools.vscode-docker
    - code --install-extension editorconfig.editorconfig
    - code --install-extension eamodio.gitlens
    - code --install-extension shd101wyy.markdown-preview-enhanced 
    - code --install-extension ryu1kn.partial-diff
    - code --install-extension felixfbecker.php-debug
    - code --install-extension neilbrayfield.php-docblocker
    - code --install-extension bmewburn.vscode-intelephense-client
    - code --install-extension ecodes.vscode-phpmd
    - code --install-extension breezelin.phpstan
    - code --install-extension ikappas.phpcs
    - code --install-extension kokororin.vscode-phpfmt
    # GIT
    - git config --global user.email "$(whoami)@$(whoami)"
    - git config --global user.name "$(whoami)"
    - git config --global core.editor vim
    - git config --global alias.ignore '!git update-index --assume-unchanged'
    - git config --global alias.unignore '!git update-index --no-assume-unchanged'
    - git config --global alias.ignored '!git ls-files -v | grep ^[a-z]'
    - git config --global alias.clone-branches '! git branch -a | sed -n "/\/HEAD /d; /\/master$/d; /remotes/p;" | xargs -L1 git checkout -t'
#########################################################################################
