---
- name: Instala Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: a+x
