- name: ZSH > Install packages
  apt: name={{ item }} state=present
  loop: 
    - zsh # shell with lots of features

#########################################################################################  
# TODO : definir 'yes' durante a instalação
# - name: Oh My Zsh > SETUP
#   shell: "{{item}}"
#   become: true
#   become_user: "{{current_user}}"
#   with_items:
#     - sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

#########################################################################################
